[{
    "company_name":"hcl",
    "date":ISODate("2020-09-25"),
    "students_appeared":"hari,peter,prashal,selvan,dinesh"
},
{
    "company_name":"cts",
    "date":ISODate("2020-10-16"),
    "students_appeared":"shanthini,sindhuja,abdul,thirumaaran,muthu"
},
{
    "company_name":"tcs",
    "date":ISODate("2020-10-27"),
    "students_appeared":"abirami,keni,josco,subash,zuber"
},
{
    "company_name":"zoho",
    "date":ISODate("2020-11-15"),
    "students_appeared":"naveen,suvan,felix,jethro,ashwin"
},
{
    "company_name":"guvi",
    "date":ISODate("2020-11-25"),
    "students_appeared":"jeshwin,jack,rohit,yogesh,edwin"
}]